#!/usr/bin/env node
import { fetchDigestData } from './github.js';
import { renderDigest, generateTitle, calculateActivityCount } from './digest.js';
import type { Config } from './types.js';

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const options = parseArgs(args);

  if (options.help) {
    printHelp();
    process.exit(0);
  }

  if (!options.repo) {
    console.error('Error: --repo is required (format: owner/name)');
    printHelp();
    process.exit(1);
  }

  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    console.error('Error: GITHUB_TOKEN environment variable is required');
    process.exit(1);
  }

  const [owner, repo] = options.repo.split('/');
  if (!owner || !repo) {
    console.error('Error: --repo must be in format owner/name');
    process.exit(1);
  }

  const config: Config = {
    discussionCategory: options.category || 'General',
    sinceDays: options.days || 7,
    maxPrs: options.maxPrs || 10,
    maxNewContributors: options.maxContributors || 10,
    minActivity: options.minActivity || 3,
    dryRun: options.dryRun || true, // CLI always dry-run by default
    footerStarLink: options.footer !== false,
    owner,
    repo,
  };

  console.log(`Fetching digest data for ${owner}/${repo}...`);
  console.log(`Looking back ${config.sinceDays} days\n`);

  try {
    const data = await fetchDigestData(token, config);
    const activityCount = calculateActivityCount(data);

    console.log(`Found ${data.mergedPRs.length} merged PRs`);
    console.log(`Found ${data.newContributors.length} new contributors`);
    console.log(`Total activity count: ${activityCount}\n`);

    if (activityCount < config.minActivity) {
      console.log(
        `Activity count (${activityCount}) is below threshold (${config.minActivity}).`
      );
      console.log('A real run would skip posting this week.\n');
    }

    const markdown = renderDigest(data, config);
    const title = generateTitle(data.periodEnd);

    console.log('='.repeat(60));
    console.log(`Title: ${title}`);
    console.log('='.repeat(60));
    console.log(markdown);
    console.log('='.repeat(60));
  } catch (error) {
    if (error instanceof Error) {
      console.error(`Error: ${error.message}`);
    } else {
      console.error('An unexpected error occurred');
    }
    process.exit(1);
  }
}

interface CLIOptions {
  help?: boolean;
  repo?: string;
  category?: string;
  days?: number;
  maxPrs?: number;
  maxContributors?: number;
  minActivity?: number;
  dryRun?: boolean;
  footer?: boolean;
}

function parseArgs(args: string[]): CLIOptions {
  const options: CLIOptions = {};

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    const next = args[i + 1];

    switch (arg) {
      case '--help':
      case '-h':
        options.help = true;
        break;
      case '--repo':
      case '-r':
        options.repo = next;
        i++;
        break;
      case '--category':
      case '-c':
        options.category = next;
        i++;
        break;
      case '--days':
      case '-d':
        options.days = parseInt(next, 10);
        i++;
        break;
      case '--max-prs':
        options.maxPrs = parseInt(next, 10);
        i++;
        break;
      case '--max-contributors':
        options.maxContributors = parseInt(next, 10);
        i++;
        break;
      case '--min-activity':
        options.minActivity = parseInt(next, 10);
        i++;
        break;
      case '--dry-run':
        options.dryRun = true;
        break;
      case '--no-footer':
        options.footer = false;
        break;
    }
  }

  return options;
}

function printHelp(): void {
  console.log(`
community-digest-action CLI

Usage: pnpm dev -- [options]

Options:
  -h, --help              Show this help message
  -r, --repo <owner/name> Repository to generate digest for (required)
  -c, --category <name>   Discussion category (default: General)
  -d, --days <n>          Lookback window in days (default: 7)
  --max-prs <n>           Max merged PRs to include (default: 10)
  --max-contributors <n>  Max new contributors to list (default: 10)
  --min-activity <n>      Minimum activity threshold (default: 3)
  --dry-run               Don't post (always true for CLI)
  --no-footer             Omit the "Generated by" footer

Environment:
  GITHUB_TOKEN            GitHub token for API access (required)

Examples:
  pnpm dev -- --repo octocat/hello-world
  pnpm dev -- --repo octocat/hello-world --days 14 --max-prs 5
`);
}

main();
