import type { Config, DigestData } from './types.js';

export function renderDigest(data: DigestData, config: Config): string {
  const lines: string[] = [];

  // Period header
  const periodStr = formatDateRange(data.periodStart, data.periodEnd);
  lines.push(`# Weekly Digest — ${periodStr}`);
  lines.push('');

  // Merged PRs section
  if (data.mergedPRs.length > 0) {
    lines.push('## Merged Pull Requests');
    lines.push('');
    for (const pr of data.mergedPRs) {
      lines.push(
        `- [#${pr.number}](${pr.url}) ${pr.title} — [@${pr.author}](${pr.authorUrl})`
      );
    }
    lines.push('');
  }

  // New contributors section
  if (data.newContributors.length > 0) {
    lines.push('## New Contributors');
    lines.push('');
    lines.push(
      `Welcome to our newest contributors! Thank you for your first contribution.`
    );
    lines.push('');
    for (const contributor of data.newContributors) {
      lines.push(
        `- [@${contributor.login}](${contributor.url}) in [#${contributor.prNumber}](${contributor.prUrl})`
      );
    }
    lines.push('');
  }

  // Summary
  lines.push('---');
  lines.push('');
  const prCount = data.mergedPRs.length;
  const contributorCount = data.newContributors.length;
  const parts: string[] = [];
  if (prCount > 0) {
    parts.push(`${prCount} PR${prCount === 1 ? '' : 's'} merged`);
  }
  if (contributorCount > 0) {
    parts.push(
      `${contributorCount} new contributor${contributorCount === 1 ? '' : 's'}`
    );
  }
  if (parts.length > 0) {
    lines.push(`*${parts.join(' • ')}*`);
    lines.push('');
  }

  // Footer with star link
  if (config.footerStarLink) {
    lines.push('---');
    lines.push('');
    lines.push(
      `*Generated by [community-digest-action](https://github.com/malmichaels-gif/community-digest-action) — ` +
        `[give it a star](https://github.com/malmichaels-gif/community-digest-action) if you find it useful!*`
    );
  }

  return lines.join('\n');
}

export function generateTitle(periodEnd: Date): string {
  const dateStr = formatDate(periodEnd);
  return `Weekly Digest — ${dateStr}`;
}

export function calculateActivityCount(data: DigestData): number {
  return data.mergedPRs.length + data.newContributors.length;
}

function formatDate(date: Date): string {
  return date.toISOString().split('T')[0];
}

function formatDateRange(start: Date, end: Date): string {
  return `${formatDate(start)} to ${formatDate(end)}`;
}
