import { describe, it, expect } from 'vitest';
import { renderDigest, generateTitle, calculateActivityCount } from './digest.js';
import type { Config, DigestData } from './types.js';

const baseConfig: Config = {
  discussionCategory: 'Weekly Updates',
  sinceDays: 7,
  maxPrs: 10,
  maxNewContributors: 10,
  minActivity: 3,
  dryRun: false,
  footerStarLink: true,
  owner: 'test-owner',
  repo: 'test-repo',
};

const baseData: DigestData = {
  mergedPRs: [
    {
      number: 123,
      title: 'Add new feature',
      url: 'https://github.com/test/repo/pull/123',
      author: 'alice',
      authorUrl: 'https://github.com/alice',
      mergedAt: '2026-01-10T12:00:00Z',
    },
    {
      number: 124,
      title: 'Fix bug in parser',
      url: 'https://github.com/test/repo/pull/124',
      author: 'bob',
      authorUrl: 'https://github.com/bob',
      mergedAt: '2026-01-11T12:00:00Z',
    },
  ],
  newContributors: [
    {
      login: 'alice',
      url: 'https://github.com/alice',
      prNumber: 123,
      prTitle: 'Add new feature',
      prUrl: 'https://github.com/test/repo/pull/123',
    },
  ],
  periodStart: new Date('2026-01-07'),
  periodEnd: new Date('2026-01-14'),
};

describe('renderDigest', () => {
  it('renders merged PRs section', () => {
    const markdown = renderDigest(baseData, baseConfig);
    expect(markdown).toContain('## Merged Pull Requests');
    expect(markdown).toContain('[#123]');
    expect(markdown).toContain('Add new feature');
    expect(markdown).toContain('[@alice]');
  });

  it('renders new contributors section', () => {
    const markdown = renderDigest(baseData, baseConfig);
    expect(markdown).toContain('## New Contributors');
    expect(markdown).toContain('[@alice]');
    expect(markdown).toContain('in [#123]');
  });

  it('includes footer when enabled', () => {
    const markdown = renderDigest(baseData, baseConfig);
    expect(markdown).toContain('Generated by');
    expect(markdown).toContain('community-digest-action');
  });

  it('omits footer when disabled', () => {
    const config = { ...baseConfig, footerStarLink: false };
    const markdown = renderDigest(baseData, config);
    expect(markdown).not.toContain('Generated by');
  });

  it('renders summary with counts', () => {
    const markdown = renderDigest(baseData, baseConfig);
    expect(markdown).toContain('2 PRs merged');
    expect(markdown).toContain('1 new contributor');
  });

  it('handles empty data gracefully', () => {
    const emptyData: DigestData = {
      mergedPRs: [],
      newContributors: [],
      periodStart: new Date('2026-01-07'),
      periodEnd: new Date('2026-01-14'),
    };
    const markdown = renderDigest(emptyData, baseConfig);
    expect(markdown).toContain('Weekly Digest');
    expect(markdown).not.toContain('## Merged Pull Requests');
    expect(markdown).not.toContain('## New Contributors');
  });
});

describe('generateTitle', () => {
  it('generates title with date', () => {
    const title = generateTitle(new Date('2026-01-14'));
    expect(title).toBe('Weekly Digest — 2026-01-14');
  });
});

describe('calculateActivityCount', () => {
  it('sums PRs and new contributors', () => {
    const count = calculateActivityCount(baseData);
    expect(count).toBe(3); // 2 PRs + 1 new contributor
  });

  it('returns 0 for empty data', () => {
    const emptyData: DigestData = {
      mergedPRs: [],
      newContributors: [],
      periodStart: new Date(),
      periodEnd: new Date(),
    };
    const count = calculateActivityCount(emptyData);
    expect(count).toBe(0);
  });
});
